### ISSUE TITLE
Forward feature of django autocomplete light not working

### ISSUE THREAD

**Issue by farhan-cashify** [shamanu4/dal_admin_filters#19]
I would like to send some field in forward arguments like django autocomplete light.
I tried sending them but could not succeed.
Any Idea ?

**Comment by farhan-cashify** [comment]
Actually **select2.js** was expecting the autocomplete widget inside a **form**, which in case of list filter was absent. As a result ,the forward field was not being forwarded.
Just enclosed it inside form tag and started working.
Hope it helps someone.

**Comment by shamanu4** [comment]
Fixed in 1.0.0
