### ISSUE TITLE
Pass in values from other admin filters

### ISSUE THREAD

**Issue by selected-pixel-jameson** [shamanu4/dal_admin_filters#21]
Is there a way to pass in a value from a different filter so that we can only display the subset of values? For example I have Publishers which contain Series and I'd like to only show the series that are available within a particular publisher if there is a filter set for publisher. 

I think that this might be possible using DAL's forward mechanics, but I have no idea how I would implement that with this module.

**Comment by shamanu4** [comment]
This feature is available from version 1.0.0
